service: YOUR_SERVICE
app: YOUR_APPNAME
org: YOUR_ORG

provider:
  name: aws
  runtime: nodejs12.x
  region: YOUR_REGION
  stage: dev
  environment:
    prefix: niod
    DYNAMODB_TABLE: Rydes
    DOMAIN_SUFFIX: tld
    
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:*:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  teapot:
    handler: src/backend/teapot.hello
    environment:
      USER_POOL_ID: !Ref cognitoUserPool
      USER_POOL_CLIENT_ID: !Ref cognitoUserPoolClient
    events:
      - http:
          path: /teapot  
          method: get    
          cors: true # adds an OPTIONS method with Origin: * to the Endpoint
          integration: lambda # suggested fix for error in AWS API testing "Lambda execution failed with status 200 due to customer function error: Cannot read property 'X-Amzn-Trace-Id' of null"      

  RequestUnicorn:
    handler: src/backend/requestUnicorn.handler
    environment:
      USER_POOL_ID: !Ref cognitoUserPool
      USER_POOL_CLIENT_ID: !Ref cognitoUserPoolClient

    events:
     - http:
          path: /rides  
          method: post    
          cors: true # adds an OPTIONS method with Origin: * to the Endpoint
          integration: lambda # default: lambda-proxy. exposes claims at event.requestContext.authorizer.claims

plugins:
  - serverless-finch

custom:
  client:
    bucketName: ${self:provider.environment.prefix}-wildrydes
    distributionFolder: src/frontend
    errorDocument: index.html
  
resources:
  Resources:
    # the user pool
    cognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        # Generate a name based on the stage
        UserPoolName: ${self:provider.environment.prefix}-${self:service}-user-pool
        # Set email as an alias
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    # the client for the frontend app
    cognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        # Generate an app client name based on the stage
        ClientName: ${self:provider.environment.prefix}-${self:service}-user-pool-client
        UserPoolId:
          Ref: cognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false
    # a specific resource
    RidesTable:
      # of type dynamodb table 
      Type: AWS::DynamoDB::Table
      Properties:
        # refer to environmental variable for name provider.environment....
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        # columns
        AttributeDefinitions:
          - AttributeName: RideId
            # type string
            AttributeType: S
        # primary key
        KeySchema:
          - AttributeName: RideId
            KeyType: HASH
        # capacity of the table for cost management, tune according to requirements
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
